### ISSUE TITLE
Narrow down a paper topic 

### ISSUE THREAD

**Issue by chrisvarga** [chrisvarga/chatbot#1]
Maybe we could look at the "future research" sections of these papers and try to improve their strategy.

**Comment by nmarble** [comment]
I say we do one of two things:
1. Create a chatbot that uses twitter for responses like in one of the papers that you referenced.
2. Start with a blank database that consistently updates and gets better the more you talk to it.

**Comment by chrisvarga** [comment]
Or we could think of our own idea too, it doesn't necessarily have to build on the papers I suppose.

**Comment by chrisvarga** [comment]
Dude, I think I found the jackpot library (pattern) we could use for Twitter and Machine Learning/Natural Language Processing/Artificial Intelligence! (http://www.clips.ua.ac.be/pattern). I like how as opposed to the python-twitter module, you don't have to create a Twitter account and setup OAuth to use the pattern module.

Here's an example of how simple it is to use with Twitter (from their site):

>>> from pattern.web import Twitter, plaintext
>>>
>>> twitter = Twitter(language='en') 
>>> for tweet in twitter.search('"more important than"', cached=False):
>>>    print plaintext(tweet.text)
 
'The mobile web is more important than mobile apps.'
'Start slowly, direction is more important than speed.'
'Imagination is more important than knowledge. - Albert Einstein'
...

**Comment by nmarble** [comment]
I tried out the library and it seems to work nice, I did notice it has a query limit of 600 per hour (150 per 15min) with 3000 results max on each. Do you think this would be limiting in any way? 

I like the pattern.en library seems to have a lot off useful things, that were mention in parsing the sentences. 

I added a test code: mostly just to try out a new environment. It can be deleted.

**Comment by chrisvarga** [comment]
After reading a few more papers, I'm starting to think that a paper topic as broad as "making a better chatbot" will be difficult. Maybe our paper could just focus on just one aspect of the Twitter parsing used for chatbots. For example, we could look at the specific algorithms to tell whether to classify a tweet as a question, opinion statement (i.e I like X), or personal status update (i.e. I am happy today). Then we could modify one of the algorithms and quantitatively compare ours to another one by seeing whether it classifies a particular convoluted sentence we come up with successfully. Just a thought.

**Comment by nmarble** [comment]
Though I do agree the topic is very broad, If we were to narrow it down even more I would prefer to keep in the direction of the chatbot rather than just parsing data. We could simple take a a database of q and a's like you initially suggested. To measure success could be a percentage of sentences it is able to recognize and for the hypotheses it can be as simple as using X algorithm to search the database we are able to come up with a proper response Y% of the time. 

If you wanted to change to a even more quantitative Idea,  we could do something along the lines of "20 questions" that can be played both by asking questions to find an answer and having the computer ask you questions to guess an answer. We could accomplish this by using machine learning to assign values to certain questions it ask the more it is used the better it gets.

**Comment by nmarble** [comment]
Basic layout.

Input -> Input Classification ->Decide what to Search for -> Pick from query -> respond -> (Future) response parsing
