### ISSUE TITLE
Proposal Evaluation Methods

### ISSUE THREAD

**Issue by nmarble** [chrisvarga/chatbot#6]
Write Proposal Evaluation Methods section (Section 4)

References here: #8

**Comment by chrisvarga** [comment]
## Evaluation Methods
We will evaluate the effectiveness of our chatbot both qualitatively and quantitatively. First, to evaluate our chatbot qualitatively, we will ask a specific question, and then determine whether the response from the chatbot seemed human-like. This evaluation method will obviously necessarily require a degree of subjectivity, but will nonetheless allow us to judge the relative effectiveness of the chatbot in holding a conversation.

Second, in order to quantitatively evaluate the effectiveness of our chatbot, we will adopt a method inspired by Ritter et al. [1]. This method will attempt to objectively rate the conversational accuracy of the chatbot in terms of its ability to replicate an actual twitter conversation. In other words, we will use a real tweet as input to the chatbot. Then, we will expect the response given by the chatbot to be the actual tweet given by a human in a real world conversation. We will rate the overall effectiveness of the chatbot by calculating the percentage of conversations it correctly predicted. We will consider our chatbot to be a success if it's percentage of correct conversation predictions is near 80%.

## References for this section
[1] Ritter, A., Cherry, C., & Dolan, B. (2010, June). Unsupervised modeling of twitter conversations. In Human Language Technologies: The 2010 Annual Conference of the North American Chapter of the Association for Computational Linguistics (pp. 172-180). Association for Computational Linguistics.
