### ISSUE TITLE
Combine Proposal Paper Section

### ISSUE THREAD

**Issue by nmarble** [chrisvarga/chatbot#9]
Combine all of the Proposal Paper sections into one

**Comment by chrisvarga** [comment]
Title idea: **An Experimental Application of Unsupervised Modeling to Chatbots**

We will probably draw heavily upon the classification schemes and evaluation methods of "Unsupervised Modeling of Twitter Conversations" in our paper, so a title something like that makes sense to me. Any thoughts?

**Comment by nmarble** [comment]
I concur on the title,

> An Experimental Application of Unsupervised Modeling to Chatbots

**Comment by nmarble** [comment]
I believe we are completed with all the sections. I am not familiar with latex. Are you able to combine them all or should I read how to do it?

**Comment by nmarble** [comment]
I just noticed that the implementation section still references using a database. Will we be taking that part out?

**Comment by chrisvarga** [comment]
Ya I'm working on the latex, and should have it finished tomorrow afternoon. As for the database, I don't think that a database itself is necessarily a problem, as long as we are clear that it is a dynamic database that is continuously updating as opposed to the ALIZA way which was permanent and never updated. We can still make it so that each question to the chatbot does a new query to Twitter and updates the tweets database. The machine learning algorithms I was looking at all worked better with a bigger dataset than a single Twitter query could provide though.

**Comment by nmarble** [comment]
That is fine, be aware thoug,h that my introduction mentions not having a static database. Though it may still not necessarily be a static database.

**Comment by chrisvarga** [comment]
Gotcha ya. I guess you saw that I modified the introduction a bit to allow for a dynamic database. ^-^

**Comment by nmarble** [comment]
https://github.com/chrisvarga/chatbot/blob/master/experimental-application-unsupervised.pdf
